# Homework on Statistical Learning Theory

<b>Deadline:</b> 24.12.2018, 9 a.m. (there would be no soft deadline)

<b>How to hang in?</b> You need to put your Jupyter Notebook to GitHub repo and send link in Telegram to <b>@CroCode</b>

In [ ]:
PACO AREVALO REYES

### Block №1. Combinatorics and Probability Theory

You can use LaTeX expressions in order to provide formulas: https://en.wikibooks.org/wiki/LaTeX

1) In how many ways can the letters of the word PROBABILITY be rearranged such that all I’s and P’s appear in the middle?

<b>Total:</b> 1 point

In [ ]:
ANSWER=9!-4*8!+2*7!

2) The probability of having defect (at least 1 defective product) in batch of 100 products is 63.2%. Find the probability of having less than 3 defective products in such a batch.

<i>Hint:</i> use idea of Poisson distribution (https://en.wikipedia.org/wiki/Poisson_distribution)

<b>Total:</b> 1.5 points

In [ ]:
P(X>=1)=0.632
P(X=0)=1-0.632=0.368
P(X=k)=e^(-λ)*(λ)^k/(k!)
P(X=0)=e^(-λ)
λ=-log(-0.368)=0.9728611
P(X=1)=0.368
P(X=2)=e^(-λ)*(λ)^2/(2!)=0.1788807
P(X=0)+P(X=1)+P(X=2)=0.368+0.368+0.1788807
P(X<3)=0.368+0.368+0.1788807=0.9148807=91.49%

### Block №2. Data Structures and Algorithms

<b><i>NB!</i></b> Here you need to provide solution having minimal memory and runtime complexity in terms of Big O notation.

3) Suggest an algorithm that resets all elements in the column <i>i</i> and the row <i>j</i> of the matrix M to zeros if the element in the <i>(i, j)</i> cell is zero. Provide solution having minimal memory and runtime complexity in terms of Big O notation.

<b>Input:</b> matrix M

<b>Output:</b> modified according to condition matrix M

<b>Total:</b> 2 points

In [3]:
import numpy as np

def setmatrix(M):
    # We check zeros in 1st row and 1st column and save it in two boolean variables
    row_aux = False #Initilize the logical variable for row
    col_aux = False #Initilize the logical variables for column
    # If at least one zero is founded in the first row and column
    #the boolean variables will be set to True
    
    
    # In the first round we just set the row and column boolean variables
    # and modify the first row and first column of matrix
    
    for i in range(0, len(M)) : 
          
        for j in range(0, len(M[i])) : 
            if (i == 0 and M[i][j] == 0) : 
                row_aux = True
                      
            if (j == 0 and M[i][j] == 0) : 
                col_aux = True
              
            if (M[i][j] == 0) : 
                M[0][j] = 0
                M[i][0] = 0
                  
    #We save the information about the existence of zero cells in the first row
    #and first column, then we will use this information for setting the remaining
    #cells
    
    #With the previous information and the actual conditions we modify
    #the submatrix (m-1)*(n-1)
    
    for i in range(1, len(M)) : 
          
        for j in range(1, len(M[i])) : 
            if (M[0][j] == 0 or M[i][0] == 0) : 
                M[i][j] = 0
    # With the information saved in 1st row and 1st column we set to zero the 
    #i-j cells of matrix
    if (row_aux == True) : 
        for i in range(0, len(M[i])) : 
            M[0][i] = 0
    #We set to zero the first row if a zero existed in it.
    # modify first col if there was any 1 
    if (col_aux == True) : 
        for i in range(0, len(M)) : 
            M[i][0] = 0
#We set to zero the first column if a zero existed in it.
    return(M)
#Time complexity O(N*M) where N is the number of rows and M the number of columns of the matrix or array
#Memory complexity O(1).
# The code was adapted from 

4) Imagine you have a square picture, each pixel of which can be black or white (you can interpret it as binary matrix). Develop an algorithm for finding the maximum sub-square consisting of only black pixels.

<b>Input:</b> binary matrix M (contains only 0-1 elements)

<b>Output:</b> <i>((a1, b1),(a2, b2))</i> where <i>(a1, b1)</i> and <i>(a2, b2)</i> stay for coordinates of upper-left and lower-right sub-square corners respectively

<b>Total:</b> 2.5 points

In [2]:
import numpy as np

def submatrix(M):
    K=np.matrix(np.zeros((len(M),len(M)))) #Set a zero auxiliar matrix with the original matrix size
    K[0,:]=np.copy(M[0,:]) #####Set the first row with the original M values
    K[:,0]=np.reshape(np.copy(M[:,0]),(len(M),1)) #####Set the first column with the original M values
    #We`ll look for values different to zero in the submatrix M[1:,1:]
    ###that are different to zero. We get the size of the biggest left-upper
    ### matrix which contains ones in all cells. The size is setting in the
    ####K[i,j] cell.
    for i in range(1, len(M)) : 
        for j in range(1, len(M)):
                if(M[i,j]==1):
                    K[i,j]=(min(K[i,j-1], K[i-1,j], 
                                K[i-1,j-1]) + 1)
                else: ###If M[i,j] is equal to zero the value is setting to zero
                    K[i,j] = 0
                    
    K_m = K[0,0] #### We set the max size of ones sub matrix to zero
    i_m = 0  #### We set the row index of solution submatrix to zero
    j_m = 0 #### We set the col index of solution submatrix to zero
    #### We look for the coordinates of submatrix taking in consideration
    #### the values of the max submatrix sizes founded in the previos 
    ### double loop. If the size founded is greater than the previous one
    ### the value of max size and the row and column coordinates change.
    for i in range(1, len(M)): 
        for j in range(1, len(M)): 
            if (K_m < K[i,j]): 
                K_m = K[i,j] ###If the size of greates one submatrix founded is greater
                ##### than the previous one size founded, the values of size and coordinates
                ##### are updated
                i_m = i 
                j_m = j 
    print('(a1,b1)=(',int(i_m-K_m+1),',',int(j_m-K_m+1),')') ###print the solution
    print('(a1,b1)=(',int(i_m),',',int(j_m),')')             ###print the solution
    print(M[int(i_m-K_m+1):int(i_m)+1,int(j_m-K_m+1):int(j_m)+1]) ###print the submatrix

#####Code Implementation
n=10 ######define the size of matrix
#########Create a matrix with the specified size
X=(np.reshape(np.random.binomial(1, 0.8, n*n),(n,n)))
M=np.copy(X) ################Generating a copy of matrix######
submatrix(M) ################Result of program##############

#Time complexity O(N*N) where N is the size of matrix
#Memory complexity O(N*N).
# The code was adapted from 

(a1,b1)=( 1 , 3 )
(a1,b1)=( 3 , 5 )
[[1 1 1]
 [1 1 1]
 [1 1 1]]


5) Imagine series of integer numbers having only 3, 5 or 7 of some power in their factorization (i.e. 1, 3, 5, 7, 9, 15 etc.). Given k you're asked to return k-th number in this series.

<i>Helpful link</i>: https://en.wikipedia.org/wiki/Fundamental_theorem_of_arithmetic

<b>Input:</b> integer number k

<b>Output:</b> k-th number of series

<b>Total:</b> 3 points

In [ ]:
# put your code with comments here

# Memory complexity: ...
# Runtime complexity: ...